from pydantic import BaseModel, Field
from typing import Literal, Optional

OcrTaskType = Literal["pdf_digital", "pdf_scanned", "image", "youtube"]


class OcrResult(BaseModel):
    """Response returned directly after OCR processing."""

    job_type: OcrTaskType
    original_filename: str | None = None
    page_count: int = 0
    result_md: str


class YoutubeLanguage(BaseModel):
    """A single available transcript language."""

    language: str = Field(..., description="Language name, e.g. 'Vietnamese'")
    language_code: str = Field(..., description="BCP-47 code, e.g. 'vi'")
    is_generated: bool = Field(False, description="True if auto-generated by YouTube")


class YoutubeVerifyResponse(BaseModel):
    """Response from /youtube/verify — video metadata + available languages."""

    video_id: str
    title: Optional[str] = None
    available_languages: list[YoutubeLanguage]


class YoutubeRequest(BaseModel):
    """Request body for YouTube transcript endpoint."""

    url: str = Field(..., description="Valid YouTube URL (youtube.com/watch?v=ID or youtu.be/ID)")
    language_code: str = Field("vi", description="BCP-47 language code to fetch, e.g. 'vi', 'en'")
